server:
  port: 8888
  
spring:
  application:
    name: prov-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MateusProvensi/config-server
          default-label: master 
          search-paths:
          - 'greeting-service'