version: '3.4'

services:
  zipkin-server:
    image: openzipkin/zipkin:2.24
    restart: always
    ports:
      - 9411:9411
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
      - provensi-network

  rabbit-mq:
    image: rabbitmq:3.9.27-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - provensi-network

  cambio-db:
    image: mysql:8.0.27
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    expose:
      - 3308
    ports:
      - 3308:3308
    networks:
      - provensi-network

  book-db:
    image: mysql:8.0.27
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    expose:
      - 3310
    ports:
      - 3310:3310
    networks:
      - provensi-network

  naming-server:
    image: mateusprovensi/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - provensi-network

  api-gateway:
    image: mateusprovensi/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      ABC: abuda
    networks:
      - provensi-network

  cambio-service:
    image: mateusprovensi/cambio-service
    restart: always
    build:
      context: .
      dockerfile: cambio-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

      spring.datasource.url: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      spring.datasource.username: root
      spring.datasource.password: admin123

      spring.flyway.url: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      spring.flyway.user: root
      spring.flyway.password: admin123
    ports:
      - 8000:8000
    depends_on:
      - naming-server
      - cambio-db
      - rabbit-mq
    networks:
      - provensi-network

  book-service:
    image: mateusprovensi/book-service
    restart: always
    build:
      context: .
      dockerfile: book-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka

      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

      spring.datasource.url: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      spring.datasource.username: root
      spring.datasource.password: admin123

      spring.flyway.url: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      spring.flyway.user: root
      spring.flyway.password: admin123
    ports:
      - 8100:8100
    depends_on:
      - naming-server
      - book-db
      - rabbit-mq
    networks:
      - provensi-network

networks:
  provensi-network:
    driver: bridge
